version: 2

# If you only want circle to run on direct commits to master, you can uncomment this out
# and uncomment the filters: *filter-only-master down below too
#
aliases:
 - &filter-only-master
   branches:
     only:
       - master

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:xenial
    # GCC is hungry.
    resource_class: large
    # Tell everyone we're using GCC 5.
    environment:
      CXX: g++-5
    steps:
      - checkout

      # Setup. Includes boost.
      - run:
          name: Setup
          command: |
            sudo ./setup_oss_toolchain.sh

      # For testing, need additional dependencies not provided by the image.
      - run:
          name: Setup for tests
          command: |
            sudo apt-get install -y --no-install-recommends dalvik-exchange openjdk-8-jdk-headless
            sudo ln -s /usr/bin/dalvik-exchange /usr/local/bin/dx

      # Configure.
      - run:
          name: Configure
          command: |
            autoreconf -ivf
            ./configure CXX="g++-5"

      # Actual build.
      - run:
          name: Build
          # The old Travis limit. Hopefully ensures GCC does
          # not die.
          command: |
            make -j4

      # Build & run tests.
      - run:
          name: Build tests
          command: |
            make -j4 check TESTS=
      - run:
          name: Run tests
          command: |
            mkdir -p /tmp/test-results
            export GTEST_OUTPUT=xml:/tmp/test-results/
            make -j4 check
      - store_test_results:
          path: /tmp/test-results

  deploy-website:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1

    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "docusaurus-bot@users.noreply.github.com"
            git config --global user.name "Website Deployment Script"
            echo "machine github.com login docusaurus-bot password $GITHUB_TOKEN" > ~/.netrc
            echo "Deploying website..."
            unset CI_PULL_REQUEST CIRCLE_PULL_REQUEST
            cd website && yarn install && GIT_USER=docusaurus-bot USE_SSH=false yarn run publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      # Note: no filter for 'build' so that pull requests get checked.
      - build
      - deploy-website:
          filters: *filter-only-master
